### ISSUE TITLE
Compose-on-kubernetes and kompose

### ISSUE THREAD

**Issue by Vad1mo** [kubernetes/kompose#1086]
Docker just announced to open source their compose to kubernetes tool. 

https://github.com/docker/compose-on-kubernetes

my question is, how does this announcement impact this project and it future and maybe it position?

**Comment by cdrage** [comment]
@Vad1mo 

No impact on future plans, we will continue to improve and release new Kompose versions. 

Due to slow-down in activity with Docker Compose, Kompose isn't as popular as it used to be during Docker Compose's hype, however, that won't impact the projects position.

Kompose has done it's job for creating an excellent tool for Docker Compose to Kubernetes conversion during the great transition to Kubernetes.

As long as Docker continues to release new Docker Compose version's and supporting it, Kompose will be there! :100:

**Comment by Vad1mo** [comment]
Adding the information you posted to the README would be great for others to relate.
