### ISSUE TITLE
Drop master/slave terminology in the docs

### ISSUE THREAD

**Issue by jrabbit** [kubernetes/kompose#1116]
I cannot possibly recommend this project if the docs are brazenly stuck in the past. Try literally any other naming scheme that doesn't involve crimes against humanity.

**Comment by xificurC** [comment]
Creating a project named [hitman](https://github.com/jrabbit/hitman) doesn't?

**Comment by cdrage** [comment]
@jrabbit 

I've opened up a PR here: https://github.com/kubernetes/kompose/pull/1123

I apologize, at the time the project started, we were using the current Kubernetes terminology.

Obviously the docs are out of date.

Note: Going to lock this since I don't want to initiate trolling / flame war :+1:
