### ISSUE TITLE
kompose secrets file location

### ISSUE THREAD

**Issue by simbamarufu1** [kubernetes/kompose#1280]
It appears there is a mismatch between where secrets are placed when using kompose vs docker compose

docker compose places secrets in the folder `/run/secrets` kompose defines the mount path for secrets in the folder `/run/secrets/{secret-name}`. This is a breaking change if you are using `kompose convert` to deploy to k8s and need both docker-compose and k8s to work

**Comment by campos-ddc** [comment]
I'm can write a PR to fix this (if I figure out how to run script tests locally), but would it even get merged? It would be a breaking change at this point (some users might be expecting their files to be coming in as directories)

**Comment by hangyan** [comment]
All contributions are welcome! But can you summrize your proposol first? Maybe an example with some explainnations

**Comment by campos-ddc** [comment]
@hangyan I'd basically change `pkg.transformer.kubernetes.kubernetes.go:ConfigSecretVolumes` to always set a `SubPath` for volume mounts.

This should make it so secrets are always mounted as single files (instead of a file inside a directory filled with symlinks).

As far as I can tell, there are two different situations happening here:

1. User defined a secret in docker-compose without a targetPath, or with targetPath being just a filename. In this case it ends up mounted as `/run/secrets/<target>/<target>` like OP mentioned. This is incompatible with docker-compose which would mount as `/run/secrets/<target>`
2. User defined a secret in docker-compose with a targetPath in a subdirectory, or with targetPath being an aboslute path. This case already gives the same result as docker-compose. For `<target>` = `mysubdir/myfile` it would create `/run/secrets/mysubdir/myfile` (technically `myfile` would be a symlink pointing to some timestamp based directory but that shouldn't be a problem here).

I haven't tested this yet, but the relevant part of `ConfigSecretVolumes` could look something like this:

```golang
// default secretConfig.Target to secretConfig.Source, just in case user was using short secret syntax or
// otherwise did not define a specific target
target := secretConfig.Target
if target == "" {
	target = secretConfig.Source
}

// if target is an absolute path, set that as the MountPath
var secretMountPath string
if strings.HasPrefix(secretConfig.Target, "/") {
	secretMountPath = target
} else {
	// if target is a relative path, prefix with "/run/secrets/" to replicate what docker-compose would do
	secretMountPath = "/run/secrets/" + target
}

// set subPath to the target filename. this ensures that we end up with a file at our MountPath instead
// of a directory with symlinks (see https://stackoverflow.com/a/68332231)
splitPath := strings.Split(target, "/")
secretFilename := splitPath[len(splitPath)-1]

volSource := api.VolumeSource{
	Secret: &api.SecretVolumeSource{
		SecretName: secretConfig.Source,
		Items: []api.KeyToPath{{
			Key:  secretConfig.Source,
			Path: secretFilename,
		}},
	},
}
```

This would make it so we always mount as files, in the same place as docker-compose, without any symlink shenanigans.
It is a breaking change because some people might be expecting this "bug" to be in place, and assuming their files are inside a subdirectory instead of in their correct place.

**Comment by sbs2001** [comment]
@campos-ddc  your proposal sounds good. To prevent existing installations from breaking, I think this behaviour should be followed only if some cmd flag is passed. That way we can have both set of behaviours peacefully.

**Comment by campos-ddc** [comment]
@sbs2001 ok, I'll do it that way. I'm going on vacation for a couple of weeks but hopefully I'll have a PR soon.
