### ISSUE TITLE
Is it possible to push image to custom container registry?

### ISSUE THREAD

**Issue by umberto10** [kubernetes/kompose#1369]
I wanted to push my just built image to my own container registry, different than docker.io, but I don't know is this possible.
I tried it after docker login, but it always attempt to push image to https://index.docker.io/v1.
![image](https://user-images.githubusercontent.com/43953088/110907202-54799600-830d-11eb-9ad2-0a3f1c190252.png)
Am I doing something wrong?

**Comment by hangyan** [comment]
I will look into it. Seems it only support to dockerhub now, but i think we can add a flag to support create private registry image name and push to it.

**Comment by umberto10** [comment]
That would be great!

**Comment by lexcao** [comment]
I will solve it.

Here are my thoughts on how I will implement it.
1. Introduce new command argument `push-image-registry` accepting the registry.
2. Handle authentication for the registry.

There are the following points to consider.
1. Registry from command argument is high priority than parsed from name of image.
2. There should be warning when specify `push-image-registry` without `push-image`, because `push-image` is false by default.
