### ISSUE TITLE
Remove Helm support

### ISSUE THREAD

**Issue by cdrage** [kubernetes/kompose#1716]
### What would you like to be added?

Removal of Helm support

### Why is this needed?

No bandwidth to constantly maintain generation of Helm charts.

Current generation of Helm charts is very outdated, does not use the latest helm version and is currently unmaintainable.

**Comment by nathanael-h** [comment]
For this feature we might drive people to use Katenary from https://github.com/metal3d/katenary/

**Comment by metal3d** [comment]
> For this feature we might drive people to use Katenary from https://github.com/metal3d/katenary/

FYI, the project is now restarted from scratch in `develop` branch. 

My tool isn't better or worse than Kompose, it just does things differently.

The principle is to produce a complete Helm Chart by proposing to set certain constraints, links, configuration (via labels in the compose file) with a whole set of rules, a proper "values" file etc...

Katenary will be released in version 3 alpha as soon as I've found a reliable means of automatic testing.

Thanks to all who have contributed. And I really wish long life to Kompose. Because it's also an excellent tool for moving towards Kubernetes.

**Comment by metal3d** [comment]
Hello, just here to say that Katenary can be tested with the master branch: https://github.com/metal3d/katenary

There are some issues that I'm working on, but I will be OK to create a Release Candidate this week.
