### ISSUE TITLE
publicly hosted API endpoint for kompose

### ISSUE THREAD

**Issue by containscafeine** [kubernetes/kompose#419]
Hey team,

We've had some discussions around it but never opened an issue, so here it is.

Does it make sense for `kompose` to have an publicly hosted API endpoint where users can just `curl` and send their Docker Compose files and it returns the converted artifacts?

I'm suggesting something like -

`curl -X POST -F file=@docker-compose.yml kompose.io/convert` and then we return Kubernetes artifacts, which can be piped directly to `kubectl create -f -`.

This will not require installing kompose, will be very useful and will be super cool to provide `kompose-as-a-service or kompaas` :)

Thoughts?

**Comment by cdrage** [comment]
@containscafeine 

As an alternative, instead of an API, it would make more sense to have a demo on http://kompose.io similar to the "Go" playground. Build it with Go as a back-end with http server + react.js / vue.js as a front-end. Simply paste your docker-compose.yaml file in and output goes the kubernetes artifacts!

**Comment by containscafeine** [comment]
@cdrage makes sense, I have no idea about web stuff, but sounds cool. It can double up as an API as well.

**Comment by cdrage** [comment]
@containscafeine yup. that's what I'm getting at :)

**Comment by cdrage** [comment]
Yup, this one should be closed :+1: Kind friends made a GUI interface which people may use as a publicly hosting conversion: http://kompose.io/integrations/#kompose-ui-by-jad-chamoun-icann-and-joe-haddad-anghami
