### ISSUE TITLE
Fatal error saying "/etc/nginx/certs": must be unique

### ISSUE THREAD

**Issue by RyoIkarashi** [kubernetes/kompose#544]
I'm using `jrcs/letsencrypt-nginx-proxy-companion` in my `docker-compose.production.yml` and `kompose -f docker-compose.production.yml up` throws an error saying

```
WARN Unsupported logging key - ignoring
WARN Volume mount on the host "/var/run/docker.sock" isn't supported - ignoring path on the host
WARN Volume mount on the host "./certs" isn't supported - ignoring path on the host
WARN Volume mount on the host "/var/run/docker.sock" isn't supported - ignoring path on the host
WARN Volume mount on the host "./certs" isn't supported - ignoring path on the host
WARN Volume mount on the host "/var/run/docker.sock" isn't supported - ignoring path on the host
WARN Volume mount on the host "./certs" isn't supported - ignoring path on the host
INFO We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead.

INFO Successfully created Service: letsencrypt
INFO Successfully created Service: proxy
FATA Error while deploying application: Deployment.extensions "letsencrypt" is invalid: spec.template.spec.containers[0].volumeMounts[4].mountPath: Invalid value: "/etc/nginx/certs": must be unique
```

How can I fix this issue?

---

My `kompose version` is `0.5.0 ()`

And my `docker-compose.production.yml` below.

```yml
version: "2"

services:

  proxy:
    image: jwilder/nginx-proxy
    privileged: true
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
    restart: always
    logging:
      options:
        max-size: 5m
        max-file: "10"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    container_name: ssl
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs:rw

networks:
  default:
    external:
      name: shared
```

**Comment by surajnarwade** [comment]
@RyoIkarashi , `HOST:CONTAINER` or an access mode `HOST:CONTAINER:ro` is not supported by kompose

**Comment by RyoIkarashi** [comment]
@surajnarwade Thanks for your quick reply! Do you have any plan to support those functionalities?

**Comment by surajnarwade** [comment]
@RyoIkarashi, it may be problematic if you have multinode clusters, it may cause troubles.
@kadel thoughts ?

**Comment by kadel** [comment]
@RyoIkarashi 
It looks like there are two issues.

One is what @surajnarwade mentioned. This is not going to work as expected, because Kompose doesn't support copying local data to Kubernetes cluster (this is what all warning about "WARN Volume mount on the host" mean.) And side effect is of this is that mounting docker.sock to container wont work also :-( But I'm not sure if that is good idea to do that in Kubernetes. Cant this app work without docker socket?

Second issue is causing that  FATAL Error. From quick look it seems like this is bug in Kompose.
Kompose generates Kubernetes Deployment with two volumeMounts for same path `/etc/nginx/certs`.
`letsencrypt` service defines volume for `/etc/nginx/certs` and also uses `volumes_from` to share all volumes from `proxy` service. `proxy` service has its own volume for same `etc/nginx/certs`. Result is that Deplyment that gets generated has two volumeMounts for same path :-(

Quick workaround for second issue would be removing `./certs:/etc/nginx/certs:rw` volume from `letsencrypt` service and changing `./certs:/etc/nginx/certs:ro` in `proxy` to `./certs:/etc/nginx/certs:rw`
Down side of this that it key will be writable in `proxy` service :-(

**Comment by surajnarwade** [comment]
I take this up

**Comment by cdrage** [comment]
I think we should FATAL. Since it's unable to transpose the volume keys to Kubernetes correctly, fataling before it get's a failing deploy would be ideal.

Although the output could be more informative / suggest an alternative?

**Comment by surajnarwade** [comment]
@cdrage yeah, FATAL with info whats happening might help, I am onto it

**Comment by kadel** [comment]
> I think we should FATAL. Since it's unable to transpose the volume keys to Kubernetes correctly, fataling before it get's a failing deploy would be ideal.
> 
> Although the output could be more informative / suggest an alternative?

I don't think that it kompose should show FATAL err if this works in docker-compose.
We should handle this in the same way as docker-compose does.
