### ISSUE TITLE
remove dependency on docker daemon for building container images

### ISSUE THREAD

**Issue by surajssd** [kubernetes/kompose#696]
As a part of removing the dependency on docker and docker daemon, I propose we use buildah for building OCI compliant images.
And as a part of this work we will also need a mechanism that helps to push the images so we can use skopeo for that.

This will make sure we can build image anywhere regardless of the docker daemon, we don't need to exec since exec is bad. We can package all this in one single binary.

Project Buildah: https://github.com/projectatomic/buildah
Skopeo project: https://github.com/projectatomic/skopeo

**Comment by cdrage** [comment]
@surajssd Once they both exit alpha / work-in-progress it will make sense to add. 

Doesn't make sense to add this to the binary however... If you're using Kompose it's assumed you have Docker installed considering you're converting. The use case as well for building / pushing too is for those whom use Docker within Kubernetes deployments. So makes sense to use a stable API (the Docker API) for builds and pushes.

**Comment by pradeepto** [comment]
Actually, Kompose never required Docker to be installed before it had the build story. Integrating with `buildah` is important because it builds OCI compliant images and this integration is definitely important to have.

Having said that, I agree that `buildah` is alpha but it is feature complete. It is very important and good to start thinking about integrating it because being an early adopter helps us with influencing the project if need be. I don't think we should remove Docker dependency though. We should implement `buildah` as a limited support.

**Comment by kadel** [comment]
I don't know about this. Kompose is a converter for **docker compose** files. Expectation is that you are using dokcer-compose  alongside with Kompose. I don't know if it is make sense to use smething else for building container than docker.

**Comment by pradeepto** [comment]
Good point, but then docker compose is for docker, we use Kompose to move to Kubernetes.

This doesn't need to be a priority issue but if images built using `buildah` can run on Kubernetes, we should support that.
