### ISSUE TITLE
Output option with convert -c fails.

### ISSUE THREAD

**Issue by jmatsushita** [kubernetes/kompose#886]
Hi there,

When using `kompose convert -c` with the `-o` option, the charts are created in the desired folder but the last step fails:
```
> kompose convert -c -o chart
kompose convert -c -o chart
INFO Kubernetes file "chart/service-service.yaml" created
INFO Kubernetes file "chart/service-deployment.yaml" created
WARN open docker-compose/templates/chart/service-service.yaml: no such file or directory
WARN open docker-compose/templates/chart/service-deployment.yaml: no such file or directory
INFO chart created in "./docker-compose/"
```

The resulting `docker-compose` folder lacks the template files:
```
> tree docker-compose
docker-compose
├── Chart.yaml
├── README.md
└── templates
```

It would be nice to be able to choose the name of the outputting directory rather than it being hardcoded to `docker-compose`.

Cheers,

Jun

**Comment by cdrage** [comment]
Honestly, charts are bit broken at the moment. Thanks for filing the issue! Hopefully it's just a simple CLI option fixed.

**Comment by jmatsushita** [comment]
Thanks for update! Can you tell me more about how they are broken? I'm looking into using `kompose` for this, so it'd be good to have a heads up! 😄

**Comment by cdrage** [comment]
@jmatsushita Ah, let me correct myself. There's not broken per-say, just a bit disorganized. Helm has changed quite a bit since the implementation was added (such as extra variables). Kompose will work fine converting to Helm no-problem, it's more.. properly naming the files, setting up comments and proper versioning within the Helm chart.

If you don't mind me asking, what's your main use-case?

I'm assuming:

Docker Compose (dev environment)
Docker Compose file -> Helm Chart (provisioning)
Then Kubernetes for deployment?

**Comment by jmatsushita** [comment]
Yes that's exactly the main use case. Glad to hear that the chart problem is mostly cosmetic :)

**Comment by hangyan** [comment]
I will take a look
