### ISSUE TITLE
docker-compose version 3.3 is not supported.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [kubernetes/kompose#914]

**Comment by cdrage** [comment]
Due to how fast Docker Compose is in terms of development, we are only cutting / supporting major releases, see: http://kompose.io/conversion/

Unfortunately, if we were to implement say... 3.3 or 3.4, not only do we have to wait for upstream to support it (either `docker/cli` or `docker/libcompose`) but there may be major changes between that release, and a new release (4).

**Comment by intellix** [comment]
Does this still apply? The later Compose file format support alsorts of deployment goodies like health checks because of Docker swarm, which probably translate quite well into Kubernetes config files. 

3.0: 2017-01-18
3.1: 2017-02-08
3.2: 2017-04-04
3.3: 2017-06-19
3.4: 2017-11-01
3.5: 2017-12-18
3.6: 2018-03-20

**Comment by mahmoudimus** [comment]
@cdrage wanted to second @intellix's comment here, it seems that there's going to be a really long wait until we get 4.0. Does it make sense to re-evaluate this stance?

**Comment by cdrage** [comment]
@intellix is right, however, we'll still always be a couple of versions behind as we implement everything.

The initial push-back that I had was the fact that docker-compose was moving (relatively) fast and it was becoming harder to keep up.

@mahmoudimus however, @hangyan has already began adding support for newer versions, starting with https://github.com/kubernetes/kompose/pull/954 we've enabled support for newer versions of 3. 

I'm not against enabling support for new versions, just as long as we support all the keys!

**Comment by mahmoudimus** [comment]
@cdrage thanks for the response, I'll try that out. Is there a PR I can submit here to update the documentation to mention this? It was a bit harder to find. Cheers.

**Comment by xianlubird** [comment]
@mahmoudimus Here https://github.com/kubernetes/kompose/pull/993
